// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TelldusApp.Logic.Rest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConfigFile
    {
        /// <summary>
        /// Initializes a new instance of the ConfigFile class.
        /// </summary>
        public ConfigFile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConfigFile class.
        /// </summary>
        public ConfigFile(string user = default(string), IList<Device> devices = default(IList<Device>), TelldusController controller = default(TelldusController))
        {
            User = user;
            Devices = devices;
            Controller = controller;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public string User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "devices")]
        public IList<Device> Devices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "controller")]
        public TelldusController Controller { get; set; }

    }
}
