// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TelldusApp.Logic.Rest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DeviceParameter
    {
        /// <summary>
        /// Initializes a new instance of the DeviceParameter class.
        /// </summary>
        public DeviceParameter()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DeviceParameter class.
        /// </summary>
        public DeviceParameter(string code = default(string), string house = default(string), string unit = default(string))
        {
            Code = code;
            House = house;
            Unit = unit;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "house")]
        public string House { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unit")]
        public string Unit { get; set; }

    }
}
