// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace TelldusApp.Logic.Rest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TelldusController
    {
        /// <summary>
        /// Initializes a new instance of the TelldusController class.
        /// </summary>
        public TelldusController()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TelldusController class.
        /// </summary>
        public TelldusController(int? id = default(int?), int? type = default(int?), string serial = default(string))
        {
            Id = id;
            Type = type;
            Serial = serial;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serial")]
        public string Serial { get; set; }

    }
}
